### ISSUE TITLE
Stuck on step 2

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/continuous-delivery-azure#10]
I am going through the course (attempting happy path) and I got stuck during step 2.

I was able to create the Azure Subscription, and find the ID. But, I get stuck when I try to run the command in my terminal with the ID, I get an error message.

[Here are the instructions I'm on - I'm getting hung up on step 6](https://github.com/githubschool/brianamarie-github-actions-continuous-delivery-azure/pull/1#issuecomment-600563984).

I should also note in step 5, I get a lot of info back, for subscriptions that I was previously unaware of. That may be irrelevant.

The output that I'm trying to use from step 5:
```
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "7*******-8***-****-****-***********7",
    "id": "2*******-3***-****-****-***********0",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Pay-As-You-Go",
    "state": "Enabled",
    "tenantId": "7*******-8***-****-****-***********7",
    "user": {
      "name": "brswift@microsoft.com",
      "type": "user"
    }
```

What I type in step 6:
```sh
az ad sp create-for-rbac --name "GitHub-Actions" --role contributor \
                          --scopes /subscriptions/2*******-3***-****-****-***********0 \
                          --sdk-auth
```

Terminal output:
```sh
Changing "GitHub-Actions" to a valid URI of "http://GitHub-Actions", which is the required format used for service principal names
Found an existing application instance of "7*******-****-****-****-***********a". We will patch it
Insufficient privileges to complete the operation.
```

> Note: The referenced ID in the output is a brand new ID and I have no idea where it came from.

cc @hectorsector @mattdavis0351 @lmkeston @mjcastner because I think you all were able to make it past this step and you may see what I'm doing wrong 👀

**Comment by hectorsector** [comment]
@brianamarie are you using a newly created Azure account? Or your GitHub-provided creds? You should create a new account -- we could put it in the course instructions but I think this really only applies to Hubbers. Maybe we can make a quick note just in case others have work accounts they want to use and run into similar issues.

**Comment by brianamarie** [comment]
@hectorsector Thank you! That's definitely what I did wrong. I do think a message may be helpful, but it also may only apply to a small set of users. 🤷‍♂ I will try this again later this week (probably Friday). I'm sorry I couldn't get through it before the ship date, but I know when I go through it and it's public it will also be awesome. 😊
