### ISSUE TITLE
Do we need PACKAGES_TOKEN?

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/continuous-delivery-azure#12]
We're declaring `PACKAGES_TOKEN` in a few places but I don't see where any workflows are using it. Is it in use by some action within the workflows @mattdavis0351? ([example](https://github.com/githubtraining/continuous-delivery-azure/blob/master/responses/05_configure-azure.md#step-5-spin-up-configure-and-destroy-azure-resources))

All places it's used:
- [`responses/05_configure-azure.md`](https://github.com/githubtraining/continuous-delivery-azure/blob/master/responses/05_configure-azure.md)
- [`responses/09_merge-trigger.md`](https://github.com/githubtraining/continuous-delivery-azure/blob/master/responses/09_merge-trigger.md)
- template repo, `azure-configuration` branch [`.github/CHANGETHIS/spinup-destroy.yml`]( https://github.com/githubtraining/continuous-delivery-azure-template/blob/azure-configuration/.github/CHANGETHIS/spinup-destroy.yml#L8)

**Comment by mattdavis0351** [comment]
@hectorsector I don't think so.  I think that is left over from testing wether to scope a PACKAGES_TOKEN or if GITHUB_TOKEN would work.

Just to verify, you never followed any step to setup a PACKAGES_TOKEN as a repo secret?  If you never set that as a repo secret, then it's 💯 not used

**Comment by hectorsector** [comment]
Awesome! No there’s no step where we set it up. Let’s leave this issue open until we remove it from all the template branches that use it and responses.

**Comment by lmkeston** [comment]
@hectorsector I made these changes as part of David's [existing pr](https://github.com/githubtraining/continuous-delivery-azure/pull/19) because testing this is such a bear.  Once the tests pass, I'll close this issue.

**Comment by lmkeston** [comment]
whoops! also needed in Step 8: Write the production deployment trigger
