### ISSUE TITLE
Step 6: Blocked if approving before label

### ISSUE THREAD

**Issue by lmkeston** [githubtraining/continuous-delivery-azure#4]
**Describe the bug**
On step 6, if you approve before applying the label, it's not recoverable.

**To Reproduce**
Step 6 Instructions:
![image](https://user-images.githubusercontent.com/57373296/76882372-efea3f00-6850-11ea-8c84-9bac145be16c.png)

1. On step 6, approve changes **_without_** applying label.
2. The bot responds appropriately, telling you the expected action was applying the label.
3. Apply the label
4. Approve again

I couldn't get past this step after completing the approve task before the label...

**Comment by hectorsector** [comment]
@lmkeston I wasn't able to reproduce it. [Here's](https://github.com/githubschool/hectorsector-github-actions-continuous-delivery-azure/pull/2) my attempt. Maybe the PR just didn't refresh in time for you? If you can reproduce it, could you leave your repo up and send me a link? That'll allow me to dig into the logs and see if I find any errors.

**Comment by lmkeston** [comment]
@hectorsector I will try and reproduce it again later today.  I bet it was a timing issue, if it worked for you.

**Comment by lmkeston** [comment]
@hectorsector this time it worked perfectly so I think it was a timing thing.  I'll go ahead and close this.
